### ISSUE TITLE
 Issue with User Creation in the App

### ISSUE THREAD

**Issue by marc-cdmon** [Protofy-xyz/Protofy#1]
Hey Team,

Hope you guys are doing awesome! 🚀 Just wanted to drop a quick note about a snag we hit with the app. We were all set to show off some cool stuff to a bunch of friends, but ran into a bit of a hiccup with user creation.

Here's what went down:

```
Error inserting initialData for:  groups
Erro:  ZodError: [
  {
    "code": "invalid_type",
    "expected": "boolean",
    "received": "undefined",
    "path": [
      "admin"
    ],
    "message": "Required"
  }
]
    at Object.get error [as error] (/Users/marc/Documents/protofy/Protofy/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/Users/marc/Documents/protofy/Protofy/node_modules/zod/lib/types.js:142:22)
    at DerivedModel.validate (/Users/marc/Documents/protofy/Protofy/packages/protolib/base/ProtoModel.ts:137:21)
    at DerivedModel.create (/Users/marc/Documents/protofy/Protofy/packages/protolib/base/ProtoModel.ts:97:173)
    at /Users/marc/Documents/protofy/Protofy/packages/protolib/api/lib/generateApi.ts:61:55
    at Array.map (<anonymous>)
    at CreateApi (/Users/marc/Documents/protofy/Protofy/packages/protolib/api/lib/generateApi.ts:58:102)
    at AutoAPI (/Users/marc/Documents/protofy/Protofy/packages/protolib/api/lib/generateApi.ts:27:21)
    at Object.<anonymous> (/Users/marc/Documents/protofy/Protofy/packages/protolib/bundles/groups/groupsAPI.ts:4:33)
    at Module._compile (node:internal/modules/cjs/loader:1233:14) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'undefined',
      path: [Array],
      message: 'Required'
    }
  ]
}
```

to reproduce:

```
git clone repo
node prepare.js
yarn
yarn start-dev-latest
```

Totally get that bugs are part of the game, just hoping you can help us get this sorted out soon. Really psyched to get back to using the app to its full potential!

Cheers and thanks a ton!
Marc Palau

**Comment by palaueb** [comment]
Please, solve this because I need to try the app as soon as possible. 

Thanks!

**Comment by palaueb** [comment]
Problem during installation. When the installation process fills the disk, it can break at some point when retrying the installation once.

you can close this issue (if you are not interested into add some control of interrupted process at some point or check for space before installation)
